### ISSUE TITLE
Wordpress search isn't linked to data registry

### ISSUE THREAD

**Issue by ekoner** [ThreeSixtyGiving/website#119]
You can't search the content of the data registry from the main site e.g.

http://www.threesixtygiving.org/?s=quixote+foundation&submit=Go

@caprenter advises the reference material isn't searchable either.

**Comment by caprenter** [comment]
This is because the data in those sections are pulled in my scripts and don't ever get saved/indexed in the wordpress database in the same way as regular posts and blogs do.

We're looking at providing a separate site for the reference docs that will have it's own built in search, therefore I don't think this is something we are planning to 'fix' on the wordpress.

**Comment by morchickit** [comment]
Indeed not planning to fix. May I close it?

**Comment by ekoner** [comment]
Closed.
