### ISSUE TITLE
Navigation becomes bulky if adding a new button the main navigation 

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/website#127]
I wanted to take the news section out of the "About" and call it "News & Blog" but it became to bulky. 
Can we move the whole navigation to the left so we can add more no parents pages and still keep  them all on the same line? 
<img width="721" alt="navigation" src="https://user-images.githubusercontent.com/3273659/28029789-25a86d28-6599-11e7-9979-c1665ec5275a.PNG">

@caprenter

**Comment by caprenter** [comment]
There are ways to tweak this. I have had mail today that says among other things "We're planning to make some updates to the 360Giving website - including reviewing the overall architecture, cutting some of the text and adding more images."

Is this request in the light of the above? When does it need doing?

Worth noting that in terms of the development workflow (see the README in this repo) if you are making changes to the staging site it's worth letting us know because our deployment routine could remove them if we are not careful.

**Comment by morchickit** [comment]
Thanks @caprenter ! I think it would be great if you can onboard me on the staging and deployment routine, so I will know what to expect. 

So, yes, this is part of the whole review of the site. The architecture is more about the content rather than code architecture, hence my request for tweaking the header navigation. This is not urgent but will be good to get a time estimate of how long will it take to tweak it so we can be in synced with @stevieflow as well on time. Let me set up a call about it? :-)

**Comment by caprenter** [comment]
This has been done now, and is ready for testing. I've added a dummy menu item in for news and blog, which you can tweak yourself now.

**Comment by morchickit** [comment]
Great, thanks!

**Comment by caprenter** [comment]
This has been done. Closing. Re-open if it's still a problem or needs further work
