### ISSUE TITLE
Account details for Social Plugins etc

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#17]
@timgdavies You may have suggestions for further Wordpress plugins to optimise the site.

Off the top of my head, 
search engine submission stuff
caching
social buttons
analytics

**Comment by timgdavies** [comment]
It would be good to include analytics. We can either do this through our Piwik account (there is a Wordpress Piwik plugin), or a Google Analytics account controlled by 360 Giving. 

I believe WP-Engine handle the caching already, so that isn't needed. 

For social buttons - lets wait until we are integrating these into the design and choose plugin at that point.

**Comment by caprenter** [comment]
Does 360 have a google analytics account?

Can I assign you a task of gathering all 360 account information for google analytics, social (twitter, etc) services?

**Comment by caprenter** [comment]
Renamed the issue from 'Wordpress Foo'

**Comment by stevieflow** [comment]
I think this can be closed - we have analytics and wordpress.com integration sorted out.  If new foo is needed, then it can be a new ticket
