### ISSUE TITLE
Use supporters from CRM API

### ISSUE THREAD

**Issue by timgdavies** [ThreeSixtyGiving/website#65]
The CRM will provide a JSON feed at http://threesixtygiving.force.com/datastore/supporter_logos with a list of organisations and their linked Logos when those organisations are tagged in the CRM for their logos to be shown.

This should be used for the list of supporters in place of logos manually curated or from the DKAN.

**Comment by caprenter** [comment]
I think we have spoken about using the Wordpress media gallery to store the Logo's that are being used on the website. (The JSON feed you supply points only to (2) logos, both of which have been uploaded to the website.) So will all the logo's for this feature be in Wordpress media gallery?

If so then we could maybe look at a plugin manager to organise the media gallery, and adapt the custom code to show only logos in a certain folder. (We would also need to add metadata to the images so that we got URL info etc)

Another alternative is to use the dcat.json which is proposed in https://github.com/ThreeSixtyGiving/website/issues/64
This also has logo info in it, and all the required associated data as far as I can tell. And I think that if logo info is in the dcat.json, then it can also be used for the supporters logos?

The current supporters logos runs off the cached data from the CKAN call. I'm thinking that the new version can run off the cached data from the salesforce api call. Otherwise we maybe need to find a way to cache the results of this 'new' call, so that we don't hit the API each time the page is loaded.

Talk to me if this is not clear!

**Comment by timgdavies** [comment]
The CRM Handbook (In WS2_Publication Google Docs folder) has details of how Logos should be handled.

There is a tick box in the CRM for Organisations to indicate whether their supporter logo should be shown in the supporter_logos feed or not.

Only two are currently ticked there - but once those records are updated, the supporter_logos feed should provide an authoritative list of logos.

It should be possible to adapt the code from the dcat.json, which implements caching, to hit this updated API.

**Comment by caprenter** [comment]
Ok, thanks. So the document you point to tells me that all the logos that will be displayed on the website will be held in the Wordpress media gallery.

There are definitely ways that we can handle showing a subset of those images on the home page without the overhead of maintaining a separate API call, and with the advantage of changes being seen to take effect immediately. 

Lets discuss.

**Comment by timgdavies** [comment]
The reason to use the API call is that someone's status as a supporter who
should have their logo displayed or not is a Relationship Management
question, so really belongs in the CRM...

On Wed, Jan 13, 2016 at 10:36 AM, caprenter notifications@github.com
wrote:

> Ok, thanks. So the document you point to tells me that all the logos that
> will be displayed on the website will be held in the Wordpress media
> gallery.
> 
> There are definitely ways that we can handle showing a subset of those
> images on the home page without the overhead of maintaining a separate API
> call, and with the advantage of changes being seen to take effect
> immediately.
> 
> Lets discuss.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ThreeSixtyGiving/website/issues/65#issuecomment-171249865
> .

## 

+44 (0)7834 856 303
@timdavies
http://www.timdavies.org.uk

**Comment by stevieflow** [comment]
Clarifying with 360 who the supporters are

**Comment by caprenter** [comment]
In the latest website design they have gone with a hand curated set of images in a slider on the home page, so this 'api' call is not doing anything
